fix truncation error in strncpy()
error: ‘__builtin_strncpy’ specified bound 8192 equals destination size [-Werror=stringop-truncation]

We can to copy at most one char less than the target buffer size
so that the final \0 can still be appended.